### ISSUE TITLE
availeble in sections but no slider display on page

### ISSUE THREAD

**Issue by LeenVerschooten** [twiro/slider#18]
I'm using symphony 2.6.3 and installed the slider extension. I'm able to choose slider in the sections, in the event I get:
  <label>
        <input name="fields[slidertest]" type="text" />
    </label>
I suppose this isn't right :)
When viewing the data in symphony the slide bar does appear.

**Comment by twiro** [comment]
As every symphony field extension the slider-field is supposed to work in the symphony admin area - **not on your frontend pages**.

If you build an event for a section Symphony will offer you "_Example Front-end Form Markup_" with which you can do whatever you want. So if you named your slider-field "slidertest" the code you posted is exactly what you're supposed to see.

You can populate this input with a single number value (e.g. "10") or a value range (e.g. "10-20") in your frontend-form and will see the submitted data as a slider in the corresponding section in the admin area. But **if you want to use a slider-interface in your frontend-form you have to build your own solution** - solving your frontend-interface-needs is not what this extension (nor any other symphony field) is meant/built for.

But given plugins like [the one](https://github.com/leongersen/noUiSlider) used in this extension it shouldn't be too hard to implement your own solution in your frontend-form.
