### ISSUE TITLE
[2.5] Cannot read property 'addClass' of undefined

### ISSUE THREAD

**Issue by nathanhornby** [twiro/slider#3]
Attempting to move the handle on the slider produces this error, and the handle won't move/change value.

> Uncaught TypeError: Cannot read property 'addClass' of undefined jquery-ui-1.8.6.custom.min.js:71

**Comment by twiro** [comment]
I'm currently updating this extension and will [replace](https://github.com/twiro/slider/issues/7) jQuery UI slider with [noUislider](http://refreshless.com/nouislider/). I assume this will fix this problem.

**Comment by twiro** [comment]
Should be fixed in version 1.2: https://github.com/twiro/slider/tree/1.2

Let me know if you run into problems again... I haven't tested the extension with Symphony 2.6.x yet, but will work on an update (including support for publish filtering) soon.
